# Generated by Django 3.2 on 2021-11-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
